### ISSUE TITLE
What are the packages you're using in the screenshots?

### ISSUE THREAD

**Issue by kuanyui** [doomemacs/themes#698]
### What would you like to know?

Excuse me, just curious what packages you are using in your screenshot to make :sweat_drops: :

1. The `M-x` on top.
2. The `M-x` candidates with their descriptions.
3. The tab bar on top.
4. The file tree at left side.

![](https://raw.githubusercontent.com/doomemacs/themes/screenshots/doom-one.png)

**Comment by jeetelongname** [comment]
1.  <https://github.com/tumashu/ivy-posframe> (:completion ivy +childfame)
2.  <https://github.com/Yevgnen/ivy-rich> (:completion ivy)
3.  <https://github.com/ema2159/centaur-tabs> (:ui tabs)
4.  <https://github.com/Alexander-Miller/treemacs/> (:ui treemacs)

do note that this screenshot is quite old and that somethings have changed since then, for example ivy is no longer the default in doom and the vertico module has taken over.
