### ISSUE TITLE
flycheck faces

### ISSUE THREAD

**Issue by nicodebo** [doomemacs/themes#719]
### What would you like to know?

Is it by design that for flycheck error/warning/info faces, for some themes the background color is lighter than the background color of the window (not sure of the terminology) while for other themes the background is exactly the same as the window's.
ex: gruvbox vs challenger deep
<img src="https://i.imgur.com/YGhN16F.png"/>
<img src="https://i.imgur.com/OihpL4D.png"/>

**Comment by hlissner** [comment]
This is intentional, yes, judging from [these lines](https://github.com/doomemacs/themes/blob/master/themes/doom-gruvbox-theme.el#L169-L171), which have existed since the theme was PRed in #277.

If you _want_ the background in challenger-deep, you can do:

```elisp
(custom-set-faces
 `(flycheck-error ((t (:background ,(doom-color 'base3)))))
 `(flycheck-warning ((t (:background ,(doom-color 'base3)))))
 `(flycheck-info ((t (:background ,(doom-color 'base3))))))
```

If you want to _remove_ it from gruvbox, then:

```elisp
(custom-set-faces
 `(flycheck-error ((t (:background nil))))
 `(flycheck-warning ((t (:background nil))))
 `(flycheck-info ((t (:background nil)))))
```

In any case, since this isn't an actionable issue I will close this. 

In the future, please post questions or discussions on [our Discourse](https://discourse.doomemacs.org) instead of our issue tracker. Thanks!

**Comment by nicodebo** [comment]
thank you very much.
