### ISSUE TITLE
Need theme

### ISSUE THREAD

**Issue by buybestonlinenow** [doomemacs/themes#724]
### Describe your request

I need them for my retail online shopping website 

### Resources

> 
Theme

**Comment by buybestonlinenow** [comment]
Yeah

**Comment by buybestonlinenow** [comment]
Sorry about spelling mistake

**Comment by hlissner** [comment]
I've closed this issue because it's unactionable, incomprehensible, and seemingly unrelated to this project--our issue tracker is only for bug reports and feature requests, not user support.

Check out [Mozilla's HTML/CSS tutorial if you're looking for help writing stylesheets](https://developer.mozilla.org/en-US/docs/Learn/CSS). If you want to use one of our themes for it, you'll find their colors near the top of their definition files. E.g. [doom-one](https://github.com/doomemacs/themes/blob/master/themes/doom-one-theme.el#L49-L83).

Good luck!
