### ISSUE TITLE
[Theme-request] winter is coming

### ISSUE THREAD

**Issue by tx46** [doomemacs/themes#743]
### Describe your request

Hey guys, I really like the Winter is Coming themes, both the dark and the light variant. I would like to port these to Doom Emacs but I have no idea how to get started.

If I get a few pointers I might be able to create the PR myself. Otherwise - would anyone else care to do it?

### Briefly explain its use-case

n/a

**Comment by hlissner** [comment]
(I moved this to doomemacs/themes, since that is our themes repo.)

I'm assuming you're referring to this [Winter is Coming](https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming) theme? I'll welcome a PR for it.

> a few pointers

1. Copy [themes/doom-one-theme.el](https://github.com/doomemacs/themes/blob/master/themes/doom-one-theme.el) to `themes/doom-winter-is-coming-theme.el`,
2. Edit the [metadata](https://github.com/doomemacs/themes/blob/master/themes/doom-one-theme.el#L3-L6) in the header comment,
3. Rename all references to `doom-one` to `doom-winter-is-coming`,
4. Adjust [the faces](https://github.com/doomemacs/themes/blob/master/themes/doom-one-theme.el#L48-L174) accordingly.

By convention, our themes avoid the following:

- Setting `:font`s or `:inherit`ing from `variable-pitch`, `fixed-pitch`, or derivative font faces. 
- Setting `:height`s for faces. E.g. `org-level-N` faces.

Hope that helps!

**Comment by philiparvidsson** [comment]
I put it under ~/.doom.d/themes but I honestly can't even figure out how to load it. How can I load the theme after I created the file so I can test the colors?

**Comment by philiparvidsson** [comment]
Just as a follow-up, I can't really get it to look good. I'm attaching the theme as it is if someone wants to work on it. I don't have the competence for this.

https://pastebin.com/uKewkm5Z

**Comment by philiparvidsson** [comment]
@hlissner how can I assign styles to certain parts of the theme, e.g., 

                 (keywords       (cyan :weight "bold))

**Comment by philiparvidsson** [comment]
![image](https://github.com/doomemacs/themes/assets/1163299/01c0f4e1-dfe3-4b17-9b05-890b0fd3b85a)

![image](https://github.com/doomemacs/themes/assets/1163299/1c6fa85a-7041-4644-8f65-74d84fcdaedd)
