### ISSUE TITLE
Add catppuccin

### ISSUE THREAD

**Issue by mateodd25** [doomemacs/themes#769]
### Describe your request

It would be nice to have the catppuccin themes on doom emacs.

### Resources

https://github.com/catppuccin/catppuccin
https://github.com/catppuccin/emacs

**Comment by elken** [comment]
#760

**Comment by gagbo** [comment]
Hello,

As mentioned earlier, there's already a PR for it. I can't say when (of if) it is going to be reviewed or accepted, but it makes the issue irrelevant anyways.

Cheers

**Comment by port19x** [comment]
Wouldn't it make more sense to link the PR instead of closing the issue?

**Comment by elken** [comment]
> Wouldn't it make more sense to link the PR instead of closing the issue?

The PR has been linked 2 messages above, which makes the issue no longer relevant and thus completed.

**Comment by port19x** [comment]
> > Wouldn't it make more sense to link the PR instead of closing the issue?
> 
> The PR has been linked 2 messages above, which makes the issue no longer relevant and thus completed.

Unfortunate wording on my end.
I meant via the Development section on the right.
![2023-01-03_14-45](https://user-images.githubusercontent.com/82055622/210369264-52e02c42-d2f9-4487-ae8a-72de65c27abf.png)

That way the issue get's closed on PR merge, meaning when the issue is actually resolved rather than merely acknowledged and being worked on

**Comment by gagbo** [comment]
It would, but usually this gets filled in automatically by github when the PR title or some commit mentions the issue: neither of those could happen here because the issue was created after the PR. Maybe this last bits will work:

Closed by #760
