### ISSUE TITLE
"Operators" syntax class ignoring variables

### ISSUE THREAD

**Issue by nicholasglazer** [doomemacs/themes#784]
### What were you expecting?

Greetings. 
I almost done with my new doom-theme, but got a weird bug related to "operators" syntax class. Maybe it's something to do with doom-one settings, since I've used that as a code template. I tried to play with settings but no luck.

### What actually happened?

As you can see on this screenshot, operators are remaining white, which is incorrect behavior, they should be blue.
![2023-05-09-09:06:13-screenshot](https://user-images.githubusercontent.com/7410355/237053096-28d323fb-1e33-4e81-8972-55c8077d4823.png)

as you can see here 
https://github.com/miozutheme/doom-miozu/blob/main/doom-miozu-theme.el#L98

### Steps to reproduce

clone https://github.com/miozutheme/doom-miozu theme into $DOOMDIR/themes/
change .config.el
`(setq doom-theme 'doom-miozu)`

https://github.com/miozutheme/doom-miozu

### Operating system

6.3.1-arch1-1

### Emacs version

Emacs 28.2 native-comp

### Installed commit of doom-themes

theme is not present yet

**Comment by hlissner** [comment]
Themes can only tell Emacs what colors/styles to apply to faces. It's up to the major mode to apply those faces to the right places in the buffer. If operators get no highlighting, it's because the mode is not parsing them, which themes are in no position to fix.

The way around this is to use tree-sitter, maybe js2-mode, maybe lsp-mode, all of which offer better syntax highlighting for the language and *may* highlight operators.

I'll close this for now, as this is unactionable, but feel free to follow up here.
