### ISSUE TITLE
Colours are different in Emacs and Emacsclient

### ISSUE THREAD

**Issue by acid-bong** [doomemacs/themes#829]
### Theme(s)

All themes (base)

### What were you expecting?

![](https://uploads.hmm.st/acidbong/PxfLcexjUqjw/1000008942.png)
When i'm launching `emacs` (on the left) or loading a theme with `M-x`, the Meow expand markers are grey.

### What actually happened?

![](https://uploads.hmm.st/acidbong/Akc3FlPATxoY/1000008943.png)
When i'm launching `emacsclient` (on the right), the expand markers have the regular background and are indistinguishable from the surrounding text (and unreadable).

### Steps to reproduce

For the first one:
1. run `emacs` (Meow is installed and set up)
2. press `e`: the markers appear for half a second

or:
1. run `emacsclient -c`
2. `M-x load-theme RET doom-gruvbox RET`
3. press `e`

For the second one:
1. run `emacsclient -c`
2. press `e`

### Operating system

NixOS unstable (pre-24.11)

### Emacs version

v29.3 +native-comp -GTK

### Installed commit of doom-themes

3b2422b208d28e8734b300cd3cc6a7f4af5eba55

**Comment by acid-bong** [comment]
Additional info: in the Emacs IRC i've been suggested to bind `(load-theme ...)` command to the first frame launching, because the theme seems to work better when it's instantly loaded into a graphical window (which is not the case with Emacs daemon and client). Haven't tried that tho

**Comment by acid-bong** [comment]
**Update:** same behaviour happens with emacs in the terminal
![image](https://github.com/doomemacs/themes/assets/94849097/5e7dc19c-6ae2-42ea-a098-d5bc425b1f44)

**Comment by hlissner** [comment]
I don't know Meow enough to suggest a proper fix, nor do I know what command is bound to `e` to quickly look it up, but I'm fairly certain this is a configuration matter rather than an issue with this package (or Meow).

There are three important milestones when starting up Emacs that this problem depends on:

1. When the first Emacs frame is created,
2. When you load the theme,
3. When you load Meow (or when Meow, presumably, performs its color lookups).

It's no. 1 that the daemon complicates. In standalone Emacs, the frame is created immediately, which is easy to deal with. In daemon Emacs, no. 1 can happen an indeterminable amount of time after Emacs is started. If no 2 and 3 occur before no 1 happens, the theme may load with a limited TTY palette, which Meow will cache and use for the rest of the session, whether or not you have a GUI or TTY frame open.j

Fixing standalone TTY Emacs is easy. Use `window-setup-hook` insetad of `after-make-frame-functions` (because the latter isn't triggered on the first/initial frame in TTY Emacs):

```elisp
(defvar theme-hook 
  (if (daemonp) 'after-make-frame-functions 'window-setup-hook))

(defun load-my-theme (&optional frame)
  (with-selected-frame (or frame (selected-frame))
    (load-theme 'doom-gruvbox t)
    (remove-hook theme-hook #'load-my-theme)))

(add-hook theme-hook #'load-my-theme)
```

This could also workaround your initial issue, so long as the first daemon frame you open isn't a TTY frame.

Hope that helps!
